name: Build and Release Busybox

on:
  workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6.0.2

    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install -y gcc make gcc-mingw-w64 libncurses-dev perl

    - name: Configure BusyBox
      run: |
          make mingw64_defconfig
          # Cleanly enable long path support if it exists as 'not set'
          if grep -q "CONFIG_FEATURE_LONG_PATHS" .config; then
            sed -i 's/# CONFIG_FEATURE_LONG_PATHS is not set/CONFIG_FEATURE_LONG_PATHS=y/' .config
          else
            echo "CONFIG_FEATURE_LONG_PATHS=y" >> .config
          fi
          cat .config

    - name: Build BusyBox
      run: make -j$(nproc)

    - name: Upload BusyBox Binary
      uses: actions/upload-artifact@v7.0.1
      with:
        path: busybox.exe
        archive: false

    - name: Create or Update GitHub Release
      uses: softprops/action-gh-release@v3.0.0
      with:
        tag_name: HEAD
        name: HEAD
        draft: false
        prerelease: true
        files: |
          busybox.exe
